charts:
  cert-manager:
  - version: 1.16.2
    appVersion: v1.16.2
  - version: 1.17.2
    appVersion: v1.17.2
  - version: 1.18.2
    appVersion: v1.18.2
  - version: 1.19.3
    appVersion: v1.19.3
  - version: 1.20.3
    appVersion: v1.20.3
  - version: 1.21.1
    appVersion: v1.21.1
