apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: prometheus
    version: 27.5.1
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_namespace: prometheus
  - name: opencost
    version: 2.5.28
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_dep_index: 0
    mcs_namespace: opencost
