st-charts:
- name: istio-ztunnel
  dep_name: ztunnel
  version: 1.24.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  dep_name: cni
  version: 1.24.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-ztunnel
  dep_name: ztunnel
  version: 1.27.1
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  dep_name: cni
  version: 1.27.1
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-ztunnel
  dep_name: ztunnel
  version: 1.28.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  dep_name: cni
  version: 1.28.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-ztunnel
  dep_name: ztunnel
  version: 1.29.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  dep_name: cni
  version: 1.29.2
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-ztunnel
  dep_name: ztunnel
  version: 1.30.3
  repository: https://istio-release.storage.googleapis.com/charts
- name: istio-cni
  dep_name: cni
  version: 1.30.3
  repository: https://istio-release.storage.googleapis.com/charts
