charts:
  istio-base:
  - version: 1.24.3
    appVersion: 1.24.3
  - version: 1.27.1
    appVersion: 1.27.1
  - version: 1.28.3
    appVersion: 1.28.3
  - version: 1.29.2
    appVersion: 1.29.2
  - version: 1.30.3
    appVersion: 1.30.3
  istiod:
  - version: 1.24.3
    appVersion: 1.24.3
  - version: 1.27.1
    appVersion: 1.27.1
  - version: 1.28.3
    appVersion: 1.28.3
  - version: 1.29.2
    appVersion: 1.29.2
  - version: 1.30.3
    appVersion: 1.30.3
  istio-gateway:
  - version: 1.24.3
    appVersion: 1.24.3
  - version: 1.27.1
    appVersion: 1.27.1
  - version: 1.28.3
    appVersion: 1.28.3
  - version: 1.29.2
    appVersion: 1.29.2
  - version: 1.30.3
    appVersion: 1.30.3
