st-charts:
- name: opensearch
  dep_name: opensearch
  version: 3.3.2
  repository: https://opensearch-project.github.io/helm-charts
- name: opensearch
  dep_name: opensearch
  version: 3.7.0
  repository: https://opensearch-project.github.io/helm-charts
