apiVersion: v2
name: example
type: application
version: 1.0.0
dependencies:
  - name: istio-base
    version: 1.30.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
  - name: istiod
    version: 1.30.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_dep_index: 0
  - name: istio-gateway
    version: 1.30.3
    repository: oci://ghcr.io/k0rdent/catalog/charts
    mcs_dep_index: 1
