apiVersion: v2
name: wandb-operator
description: A Helm chart that references the official "wandb-operator" Helm chart.
type: application
version: 1.4.9
dependencies:
  - name: operator
    version: 1.4.9
    repository: https://charts.wandb.ai
