st-charts:
- name: cilium
  dep_name: cilium
  version: 1.18.2
  repository: https://helm.cilium.io/
- name: cilium
  dep_name: cilium
  version: 1.19.6
  repository: https://helm.cilium.io/
- name: cilium
  dep_name: cilium
  version: 1.20.0
  repository: https://helm.cilium.io/
