charts:
  amd-gpu-operator:
  - version: v1.2.2
    appVersion: v1.2.2
  - version: v1.3.0
    appVersion: v1.3.0
  - version: v1.4.1
    appVersion: v1.4.1
  - version: v1.5.1
    appVersion: v1.5.1
